### ISSUE TITLE
Partition table type

### ISSUE THREAD

**Issue by jonalange** [cgsecurity/testdisk#115]
I'm not sure if this repo is still active.

In the past I didn't have to select the partition table at all. Now, about a year later I have to select it. I tested two SD cards (one actually corrupted, the other fully working).

I'm using Testdisk 7.1 and also did that in the past.

I've read the wiki about this part, but I'm still not sure what to choose.

I'm using testdisk on an iMac and I'm trying to get data from an SD card originally formatted in ExFat.

What happens if I select the wrong one? Will I put my files at risk? Or will just the scan fail? Do I have to wait until the scan is finished to see if I selected the correct one or will testdisk tell me immediately?

I'm considering "Mac" because I'm working on a Mac right now, but in the Wiki it says "EFI GPT" is for Mac, but also I use an Intel mac so maybe "Intel" is the correct one for me.

As you can see, I'm confused. If you could help me out here that would be great!
Thanks!

**Comment by JonnyTech** [comment]
The drive (SD card) can be partitioned or not depending on how you set it up. If it is partitioned then you access the volumes on the partitions. The partition type can be GPT or EFI, it will not matter for your case. Else if unpartitioned then the drive is simply one volume. I use the word volume because that is what macos generally refers to a filesystem. Testdisk will not alter the drive unless you specifically ask it to. If unsure then do whichever testdisk autodetects. Maybe disk utility may show more details.

**Comment by jonalange** [comment]
Thank you very much!
I was also on the hose (is that correct english? :D). I used photorec in the past and also wanted it this time, but started testdisk all the time.

But still your information is usefull if I want to use testdisk in the future!
